[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ki-interference"
version = "0.1.0"
description = "KI Interference"
requires-python = ">=3.9"
dependencies = [
    "mcp[cli]",
    "mcp",
    "ollama",
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "opencv-python-headless",
    "requests",
    "matplotlib",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "httpx",
]

[project.scripts]
edge-llm = "edge.llm.llm:main"
mcp-server = "edge.mcp.server.mcp_server_microscope_env:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"edge.llm" = ["*.md"]
"edge.mcp.server" = ["*.md"]

[tool.setuptools.packages.find]
where = ["src"]
